version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2
  browser-tools: circleci/browser-tools@1.1
  cloudfoundry: circleci/cloudfoundry@1.0
  slack: circleci/slack@4.3.0

commands:
  cf_deploy:
    parameters:
      space:
        type: string
      domain_prefix:
        type: string
    steps:
      - checkout
      - run:
          name: "Setup CF CLI"
          command: |
            curl -L -o cf.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=7.2.0&source=github-rel'
            sudo dpkg -i cf.deb
            cf -v
            cf api "$CF_ENDPOINT"
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
            cf install-plugin app-autoscaler-plugin -r CF-Community -f
            cf target -o "$CF_ORG" -s "<< parameters.space >>"
      - run:
          name: "Fetch existing manifest"
          command: |
            cf create-app-manifest "$CF_APP-<< parameters.domain_prefix >>" -p deploy_manifest.yml
      - run:
          name: "Push new app in dark mode"
          command: |
            # Push as "dark" instance
            cf push "$CF_APP-<< parameters.domain_prefix >>-dark" -f deploy_manifest.yml --no-route

            # Map dark route
            cf map-route  "$CF_APP-<< parameters.domain_prefix >>-dark" london.cloudapps.digital -n "$CF_APP-<< parameters.domain_prefix >>-dark"

            # Attach precreated autoscaling policy
            cf attach-autoscaling-policy "$CF_APP-<< parameters.domain_prefix >>-dark" config/autoscaling/<< parameters.space >>-policy.json

            # Enable routing from this frontend to backend applications which are private
            cf add-network-policy "$CF_APP-<< parameters.domain_prefix >>-dark" "$CF_BACKEND_APP_XI-<< parameters.domain_prefix >>" --protocol tcp --port 8080
            cf add-network-policy "$CF_APP-<< parameters.domain_prefix >>-dark" "$CF_BACKEND_APP_UK-<< parameters.domain_prefix >>"  --protocol tcp --port 8080
      - run:
          name: "Verify new version is working on dark URL."
          command: |
            sleep 15
            # TODO: Retry
            # Verify new version is working on dark URL.
            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$CF_APP-<< parameters.domain_prefix >>-dark.london.cloudapps.digital/healthcheck`
            if [ "$HTTPCODE" -ne 200 ];then
              echo "dark route not available, failing deploy ($HTTPCODE)"
              exit 1
            fi
      - run:
          name: "Switch dark app to live"
          command: |
            # Send "real" url to new version
            cf unmap-route "$CF_APP-<< parameters.domain_prefix >>-dark" london.cloudapps.digital -n "$CF_APP-<< parameters.domain_prefix >>-dark"
            cf map-route  "$CF_APP-<< parameters.domain_prefix >>-dark" london.cloudapps.digital -n "$CF_APP-<< parameters.domain_prefix >>"
            cf map-route  "$CF_APP-<< parameters.domain_prefix >>-dark" "<< parameters.domain_prefix >>".trade-tariff.service.gov.uk
            cf map-route  "$CF_APP-<< parameters.domain_prefix >>-dark" assets-<< parameters.domain_prefix >>.trade-tariff.service.gov.uk

            # Stop sending traffic to previous version
            cf unmap-route  "$CF_APP-<< parameters.domain_prefix >>" london.cloudapps.digital -n "$CF_APP-<< parameters.domain_prefix >>"

            # stop previous version
            cf stop "$CF_APP-<< parameters.domain_prefix >>"

            # delete previous version
            cf delete "$CF_APP-<< parameters.domain_prefix >>" -f

            # Switch name of "dark" version to claim correct name
            cf rename "$CF_APP-<< parameters.domain_prefix >>-dark" "$CF_APP-<< parameters.domain_prefix >>"
      - slack/notify:
          channel: deployments
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: deployments
          event: pass
          template: basic_success_1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7-node
      - image: redis
    resource_class: medium
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  checking:
    docker:
      - image: 'cimg/ruby:2.7-node'
    resource_class: small
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
      - slack/notify:
          channel: deployments
          event: fail
          template: basic_fail_1
  test:
    docker:
      - image: cimg/ruby:2.7-node
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_RETRY: "3"
          RAILS_ENV: test
    resource_class: medium
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - ruby/rspec-test
      - store_artifacts:
          path: coverage
      - slack/notify:
          channel: deployments
          event: fail
          template: basic_fail_1
  deploy_dev:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
    - cf_deploy:
        space: "development"
        domain_prefix: "dev"
  deploy_staging:
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - cf_deploy:
          space: "staging"
          domain_prefix: "staging"

workflows:
  version: 2
  build_and_test:
    jobs:
# TODO: Fix rubocop issues
#      - checking:
#          context: trade-tariff
      - test:
          context: trade-tariff
      - build:
          context: trade-tariff
          filters:
            branches:
              only:
                - master
          requires:
            - test
      - deploy_dev:
          context: trade-tariff
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - hold_staging:
          type: approval
          requires:
            - deploy_dev
      - deploy_staging:
          context: trade-tariff
          filters:
            branches:
              only:
                - master
          requires:
            - hold_staging
# TODO: Discuss production deployment strategy.
