version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1-node
      - image: redis
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
