---
version: 2.1
jobs:
  build:
    working_directory: ~/trade-tariff-frontend
    docker:
      - image: circleci/ruby:2.7.1
      environment:
        RAILS_ENV: test
  steps:
    - checkout

    # Run the tests
    - run: bundle exec rake
