name: "Development deployment"
on: [workflow_dispatch]
jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: "Deploy development"
        env:
          CF_ENDPOINT: "api.london.cloud.service.gov.uk"
          CF_SPACE: development
          CF_APP: "tariff-frontend-dev"
          CF_BACKEND_APP: "tariff-backend-dev"
          CF_BACKEND_APP_XI: "tariff-xi-backend-dev"
          CF_BACKEND_APP_UK: "tariff-uk-backend-dev"
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -L -o cf.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=7.2.0&source=github-rel'
          sudo dpkg -i cf.deb
          cf -v
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          cf install-plugin blue-green-deploy -r CF-Community -f
          cf install-plugin app-autoscaler-plugin -r CF-Community -f
          ./bin/deploy
  # sentry_release:
  #   runs-on: ubuntu-latest
  #   needs: [deploy_dev]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Create Sentry release
  #       uses: getsentry/action-release@v1
  #       env:
  #         SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  #         SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  #         SENTRY_PROJECT: tariff-frontend
  #       with:
  #         environment: development
